# Ejemplo 05
### Dr. Antonio Arista Jalife.

#### Operaciones con NumPy Arrays.
NumPy permite operaciones entre arreglos y matrices de forma sencilla. 
la operación mas sencilla es la operación "punto a punto".

In [4]:
import numpy as np

In [5]:
x = np.array([[1,2],
              [2,1]])

y = np.array([[3,4],
              [4,3]])

In [6]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[[4 6]
 [6 4]]
[[-2 -2]
 [-2 -2]]
[[3 8]
 [8 3]]
[[0.33333333 0.5       ]
 [0.5        0.33333333]]
