# Ejemplo 02
### Dr. Antonio Arista Jalife.

Como se mencionó antes, NumPy trabaja sobre arreglos y matrices. Todos los elementos de un vector, matriz, cubo, tensor, etc... son del mismo tipo. Por ello, hay una función llamada dtype que sirve para ver el tipo de dato dentro de la estructura NumPy.

In [1]:
import numpy as np

In [2]:
vectorInt = np.array([1,2,3])
vectorFloat = np.array([1.1,2.2,3.3])

print(type(vectorInt))
print(type(vectorFloat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
print(vectorInt.dtype)
print(vectorFloat.dtype)

int64
float64


Puedes forzar a que un arreglo se comporte de formas diferentes con la opción dtype.

In [4]:
vectorConvertido = np.array(vectorInt, dtype=np.float64)
print(vectorConvertido)
print(vectorConvertido.dtype)

[1. 2. 3.]
float64


### Creando matrices por primera vez.
Hay varias funciones para crear arreglos(1D), matrices(2D), cubos(3D), tensores (4D, etc... de forma automática.

In [5]:
vector = np.zeros(4) # 4 valores...
print(vector)

[0. 0. 0. 0.]


In [6]:
matriz = np.zeros((4,3)) #matriz = 4 vectores de 3 valores c/u.
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
cubo = np.zeros((4,3,2)) #cubo = 4 matrices de 3 vectores c/u, de 2 valores c/u...
print(cubo)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


Puedes usar también la función np.ones para generar una matriz de unos.

In [8]:
matriz = np.ones((3,3))
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#o bien, puedes llenar los datos de una constante.
matriz = np.ones((3,3)) * 5.0
print(matriz)

#equivalente a np.full:
print("con full:")
matriz = np.full((3,3),5.0)
print(matriz)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
con full:
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### Inicializando con valores aleatorios
De esta manera puedes crear matrices con valores aleatorios y valores aleatorios gaussianos:

In [14]:
print("Matriz aleatoria")
matrizRandom = np.random.rand(3,3)
print(matrizRandom)
print("---")
print("Matriz aleatoria gaussiana")
matrizRandomN = np.random.randn(3,3)
print(matrizRandom)

Matriz aleatoria
[[0.41115605 0.68539886 0.11356971]
 [0.89311275 0.27149753 0.05032052]
 [0.97653511 0.93052425 0.49986312]]
---
Matriz aleatoria gaussiana
[[0.41115605 0.68539886 0.11356971]
 [0.89311275 0.27149753 0.05032052]
 [0.97653511 0.93052425 0.49986312]]


### Accediendo a un dato en la matriz
De esta forma puedes acceder a datos dentro de la matriz:

In [16]:
matriz = [[0.0, 0.1, 0.2],
          [1.0, 1.1, 1.2],
          [2.0, 2.1, 2.2]]

print(matriz[2][1]) #fila 2, columna 1

2.1
